### ISSUE TITLE
Google Sign In. OAuth2 URI mismatch

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/fhir-editor#1]
Google sign in not functioning.

Account information needs updated.  @flowersw want to fix this with your account credentials?

**Comment by flowersw** [comment]
@aviars not sure I understand the problem. What needs to be done?

**Comment by rdhelms** [comment]
The URI issue has to do with the allowed origins that we have setup for use with Google's OAuth. Right now you have to be running the site from localhost. I also have it setup to accept docdish.com, whenever that is up and running.

**Comment by rdhelms** [comment]
Specifically, I believe it may only be setup for localhost:3000 right now. If you need another port allowed, just let me know and I can add it. Or else if we get it running from docdish.com, then it should also work there.

**Comment by aviars** [comment]
You need to register the app under your Google account.  I will setup docdish.com to display this a bit later today.  I'll need to move URLs around a bit.

**Comment by rdhelms** [comment]
Let me know if you need help setting up the project in your own Google Account. Once you setup a new project (at console.developers.google.com) with a new OAuth Client ID credential, we'll need to update the clientID variable in src/js/services/user.service.js.

And http://www.docdish.com will need to be added in the Google Developers dashboard for the new Client ID under "Authorized JavaScript Origins"

**Comment by aviars** [comment]
Okay I've moved things around and so I'm guessing the API calls will no longer work until adjusted.  Here's whats been done.

* docdish.com now serves fhir-editor the static JS from AWS S3. I'll create a key to update only that bucket.
* www.docdish.com now serves the static JS from Apache on the EC2 instance. Its located at /var/www/html/fhir-editror
* api.docdish.com now serves the APIs (FHIR, Djmongo, etc)

Perhaps @rdhelms we could create an Installation.md to outline where to adjust URLs and other settings.  Are those things not hard coded and adjustable all from one settings file?

cc'ing @ZachSchreiber

**Comment by aviars** [comment]
What file in the source needs modified?

**Comment by rdhelms** [comment]
Do you mean for updating the Google OAuth client ID key, or for updating the API request urls? We already updated the API request urls to match api.docdish.com so those should be fine now.

The clientID variable is in src/js/services/user.service.js as mentioned above.

Also are you periodically updating docdish.com with the most recent GitHub repo? I noticed that the site is using old code.

**Comment by aviars** [comment]
I updated the Google OAuth client ID. I updated the deployed versions you all can update the www.docdish.com version bu logging onto the the box and doing a pull.

**Comment by rdhelms** [comment]
@aviars Can you also add http://localhost:3000 back to your list of Authorized JavaScript origins in the project in your Google developer console? That's helpful for testing.

**Comment by aviars** [comment]
@rdhelms done.
