### ISSUE TITLE
Whitelabeling and Easy Configuration File to promote reuse

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/fhir-editor#2]
* Since URLs often change in deployment, we want to gather all constants into a settings file so the system can be configured in one place.  Here is a link that has some suitable approaches. http://stackoverflow.com/questions/17876439/configuration-file-in-angularjs 

* In addition, the branding "DocDish" needs to be configurable as well.

* Create a file called `CONFIGURATION.md` or `INSTALL.md` in the root of the repo explaining how/where to adjust settings.

**Comment by rdhelms** [comment]
Just pushed with a new file in src/js/configuration that contains the variables for Google OAuth and all search and update urls. Will at some point create a markdown file containing instructions for updating that.
Commit: b344e38

**Comment by aviars** [comment]
Include instructions/mission/about in whitelabling.
